### ISSUE TITLE
Trouble getting this formula to work

### ISSUE THREAD

**Issue by zlanich** [pcdummy/saltstack-lxd-formula#1]
Hey there, I'm extremely interested in using this formula, but I'm having a lot of trouble getting it to work on either Ubuntu 14.04 or 16.04. I'm wondering if you can clue me into what environment you had this working in. Here are some of the issues I'm running into:

**Scenario 1:**
- Fresh Ubuntu 14.04 via Vagrant Box: ubuntu/trusty64
- Salt installed via Vagrant's Salt Provisioner/Bootstrap
- Python version reports 2.7.6 (3 & 3.4 are also installed by default)
- pip installed via the aforementioned pip-formula
- Simple pillar set up for now: http://dp.wecreate.com/1dCVa
1. Attempt to run the "lxd" state, get failures: http://dp.wecreate.com/WjVe
2. E: Package 'criu' has no installation candidate
3. Failed to install packages: pylxd. Error: Downloading/unpacking pylxd [...] pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.5.2,!=2.8.0'))
4. Eventually got the 'criu' error to go away, but it snowballed into other Version Conflicts and eventually a compile error after upgrades.

**Scenario 2:**
- Fresh Ubuntu 16.04 via Vagrant Box: bento/ubuntu-16.04
- Salt installed via Vagrant's Salt Provisioner/Bootstrap
- Python version reports 2.7.12 (3 & 3.5 are also installed by default)
- pip installed via the aforementioned pip-formula
- Same pillar as above
1. Attempt to run the "lxd" state, get pip complaints: http://dp.wecreate.com/8B0s
2. "You are using pip version 8.1.1, however version 8.1.2 is available. You should consider upgrading..."
3. Upgraded pip to 8.1.2, left with the following errors:

```
ID: lxd_lxd
    Function: lxd.init
      Result: False
     Comment: State 'lxd.init' was not found in SLS 'lxd.lxd'
              Reason: 'lxd' __virtual__ returned False
     Started:
    Duration:
     Changes:
```

This is where I get completely lost. I'm wondering if I need some clever use of Virtual Environments and different version combinations of all these libs, but I don't even know where to begin and I can't find any clues in the docs that lead me close enough.

Please help!

Also, I see that PR [169](https://github.com/lxc/pylxd/pull/169) has been merged? What does this mean for this formula and all my aforementioned troubles?

**Comment by jochumdev** [comment]
Thirst, Thanks for using my Formula!

The easiest way to get this running is through installing pylxd with pip "pip install pylxd", at the time i developed this I had to do that. Ahh and "lxd.init" returns false cause of "lxd" and/or "lxd-client" isn't installed.

**Comment by zlanich** [comment]
Hey @pcdummy, thanks for the quick response. I think I need to add a bit of clarity though, as I've already done all of that and it still doesn't work:

Re: Ubuntu 14.04 Issues:
- Your formula has `pip install pylxd` built into it with the "use_pip" option set to "True", so it attempts to install pylxd with pip, but fails. This is where all the failures start occurring on 14.04 and there are details above. I even tried running `pip install pylxd` on its own with the same failures.

Re: Ubuntu 16.04 Issues:
- I was able to get `pip install pylxd` to work on 16.04 after upgrading pip, but it it says everything else succeeded just fine and that the lxd-client and pylxd are already installed just fine, and it still fails. Here's the full output: http://dp.wecreate.com/9xUe

Could you give me more information on the Ubuntu Release you were using, Python version pylxd was designed to run on, dependency version you had installed, etc?

Please help! I've spent over 2 full days trying to get this to work :(

**Comment by jochumdev** [comment]
Can you please join us on the IRC Channel, i might be able to give remote Hands.

The error you get looks for me like you don't have LXD installed.

**Comment by zlanich** [comment]
@pcdummy Sure thing. What time are you usually online? I'm on the East Coast. I can hop on at your convenience.

**Comment by jochumdev** [comment]
I live in Austria so GMT+1, but happily i'm online right now :)

**Comment by zlanich** [comment]
Hey, sorry I was at the gym and did not see your email. If you are online in a bit, I will be as well. Otherwise, just let me know when you are usually online and I will try to make myself available.

Best Regards,

Zach Lanich
Business Owner, Entrepreneur, Creative
Owner/Lead Developer
weCreate LLC
www.WeCreate.com

**Comment by jochumdev** [comment]
Today we had a look on that, seems like the newest version of PyLXD (2.1.x) sadly isn't compatible with this anymore.

We needed to install PyLXD Version 2.0.5 and all worked fine for us.

**Comment by zlanich** [comment]
Beat me to it! Thanks immensely for your help.
